cv_models: 
  face_detection:
    labels: coco_labels.txt
    #model: mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite
    model: ssd_mobilenet_v2_face_quant_postprocess_edgetpu.tflite
    threshold: 0.5
camera:
  index: 0
  # orientation of the camera, 0 normal, -1 flip horizontal, 1 flip vertical
  orientation: -1
  display: true
pan:
  channel: 1
  max_angle: 150
  min_angle: 10
  angle: 90
  # angle to rotate to upon shutting down
  shutdown_angle: 60
  # time to sleep when at the end of a sweep (at min angle and max angle)
  sweep_complete_sleep: 1
  # how much to step during sweep loop
  sweep_step: 0.5
  # how long to sleep when doing a step
  sweep_sleep: 0.0001
  # how much to step during tracking loop
  sweep_tracking_step: 0.1
  # how much time to sleep in between tracking seps
  sweep_tracking_sleep: 0.01
tilt:
  channel: 4
  angle: 90
  shutdown_angle: 160
  max_angle: 160
  min_angle: 90
  sweep_complete_sleep: 0.5
  sweep_step: 0.5
  sweep_sleep: 0.001
  sweep_tracking_step: 0.1  
  sweep_tracking_sleep: 0.01
sounds:
  searching: "searching.mp3"
  target_acquired: "target-acquired.mp3"
  target_lost: "are-still-there.mp3"
